# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(947, 731)
        MainWindow.setStyleSheet("\n"
"\n"
"/*-----QWidget-----*/\n"
"QWidget\n"
"{\n"
"    color: #000000;\n"
"    border-color: #000000;\n"
"    background-color: rgb(16, 10, 3);\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLabel-----*/\n"
"QLabel\n"
"{\n"
"\n"
"font-family: \'Josefin Sans\', sans-serif;\n"
"font-size: 12pt;\n"
"font-weight: 500;\n"
"letter-spacing: 0.22rem;\n"
"font-style: oblique;\n"
"text-transform: capitalize;\n"
"color: #FFFFFF;\n"
"border-radius: 1 px;\n"
"border-style: solid;\n"
"border-color: #000000;\n"
"    background-color: transparent;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QPushButton-----*/\n"
"QPushButton\n"
"{\n"
"    color: #fff;\n"
"    background-color: rgba(80, 255, 130, 200);\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-radius: 17px;\n"
"    border-color: #000;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::hover\n"
"{\n"
"    background-color: lightgrey;\n"
"    color: #000;\n"
"\n"
"}\n"
"\n"
"\n"
"QPushButton::pressed\n"
"{\n"
"    background-color: lightgreen;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QToolButton-----*/\n"
"QToolButton\n"
"{\n"
"    background-color: #292f45;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-color: #000000;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::hover\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #000000;\n"
"    padding: 2px;\n"
"    border-radius: 15px;\n"
"    border-color: #fc7c11;\n"
"\n"
"}\n"
"\n"
"\n"
"QToolButton::pressed\n"
"{\n"
"    background-color: #fc7c11;\n"
"    color: #000000;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QLineEdit-----*/\n"
"QLineEdit{\n"
"    background-color: #292f45;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-top: 0px;\n"
"    border-left: 0px;\n"
"    border-right: 0px;\n"
"    border-color: #b9b9bb;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"\n"
"/*-----QCheckBox-----*/\n"
"QCheckBox\n"
"{\n"
"    background-color: transparent;\n"
"    color: #b9b9bb;\n"
"    font-weight: bold;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator\n"
"{\n"
"    color: #b1b1b1;\n"
"    background-color: #00111d;\n"
"    border: 1px solid #f0742f;\n"
"    width: 12px;\n"
"    height: 12px;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(\"./ressources/check.png\"); /*To replace*/\n"
"    background-color: #1f2b2b;\n"
"    border: 1px solid #f0742f;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    border: 1px solid #f0742f;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::disabled\n"
"{\n"
"    color: #656565;\n"
"\n"
"}\n"
"\n"
"\n"
"QCheckBox::indicator:disabled\n"
"{\n"
"    background-color: #656565;\n"
"    color: #656565;\n"
"    border: 1px solid #656565;\n"
"\n"
"}\n"
"\n"
"QRadioButton\n"
"{\n"
"    \n"
"font-family: \'Josefin Sans\', sans-serif;\n"
"font-size: 8pt;\n"
"font-weight: 500;\n"
"    spacing: 5px;\n"
"    outline: none;\n"
"    color: #bbb;\n"
"    margin-bottom: 2px;\n"
"}\n"
"\n"
"QRadioButton:disabled\n"
"{\n"
"    color: #777777;\n"
"}\n"
"QTabBar {\n"
"\n"
"  background-color: transparent;\n"
"  height: 30px;\n"
"    font-weight: 500;\n"
"    font-size: 10pt;\n"
"    \n"
"    font-family: \"Segoe Print\";\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"border: 1px solid grey;\n"
"border-radius: 12px ;\n"
"background-color: rgba(236, 236, 236, 200);\n"
"\n"
"  border: 1px solid #CCCCCC;\n"
"  color: #333333;\n"
"  padding: 5px 10px;\n"
"  margin: 3px;\n"
" \n"
"}\n"
"\n"
"QTabWidget::tab-bar{alignment:center;}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    \n"
"  color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:repeat, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(234, 208, 174, 255), stop:0.472637 rgba(152, 97, 0, 255));\n"
"}\n"
"\n"
"QTabBar::tab:hover{\n"
"background-color: rgba(245, 245, 245, 120);\n"
"\n"
"}\n"
"\n"
"/*-----QComboBox-----*/\n"
"QComboBox\n"
"{\n"
"    padding-left: 6px;\n"
"    border: 1px solid #1d1d1d;\n"
"    background-color: rgb(158, 101, 1);\n"
"    color: #fff;\n"
"    height: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox:on\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView\n"
"{\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"    selection-background-color: #fea732;\n"
"    selection-color: #000;\n"
"    outline: 0;\n"
"\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 60, 431, 40))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Browse = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Browse.setObjectName("pushButton_Browse")
        self.horizontalLayout_3.addWidget(self.pushButton_Browse)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_property = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_property.setObjectName("comboBox_property")
        self.horizontalLayout.addWidget(self.comboBox_property)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 5)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(125, 110, 671, 541))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_view_img = QtWidgets.QLabel(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_view_img.sizePolicy().hasHeightForWidth())
        self.label_view_img.setSizePolicy(sizePolicy)
        self.label_view_img.setMouseTracking(True)
        self.label_view_img.setStyleSheet("QLabel{\n"
"border: 1px solid lightgrey;\n"
"\n"
"}")
        self.label_view_img.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_view_img.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_view_img.setText("")
        self.label_view_img.setScaledContents(True)
        self.label_view_img.setObjectName("label_view_img")
        self.verticalLayout_4.addWidget(self.label_view_img)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_t1 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_t1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_t1.setFont(font)
        self.lineEdit_t1.setObjectName("lineEdit_t1")
        self.verticalLayout.addWidget(self.lineEdit_t1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lineEdit_t2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_t2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_t2.setFont(font)
        self.lineEdit_t2.setObjectName("lineEdit_t2")
        self.verticalLayout_2.addWidget(self.lineEdit_t2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit_sd = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_sd.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_sd.setFont(font)
        self.lineEdit_sd.setObjectName("lineEdit_sd")
        self.verticalLayout_3.addWidget(self.lineEdit_sd)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Browse.setText(_translate("MainWindow", "Browse"))
        self.label.setText(_translate("MainWindow", "choose property"))
        self.label_2.setText(_translate("MainWindow", "T1"))
        self.label_3.setText(_translate("MainWindow", "T2"))
        self.label_4.setText(_translate("MainWindow", "SD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
